# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname uuid
#' @export
uuid_generate_random <- function(n = 1L) {
    .Call(`_RcppUUID_uuid_generate_random`, n)
}

#' @rdname uuid
#' @export
uuid_generate_nil <- function(n = 1L) {
    .Call(`_RcppUUID_uuid_generate_nil`, n)
}

#' @rdname uuid
#' @export
uuid_generate_name <- function(x) {
    .Call(`_RcppUUID_uuid_generate_name`, x)
}

#' @rdname uuid
#' @export
uuid_validate <- function(x) {
    .Call(`_RcppUUID_uuid_validate`, x)
}

