# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Generate a version 4 UUID
#'
#' @description
#' Function generates a new Universally Unique Identifier.
#'
#' @param n Number of generated UUIDs.
#'
#' @return Character vector with UUIDs.
#'
#' @export
#'
#' @examples
#' uuid_generate(5)
#'
uuid_generate <- function(n = 1L) {
    .Call(`_RcppUUID_uuid_generate`, n)
}

